import { wallet } from '@/near/near-setup'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [user, setUser] = useState<string | null>(null)

  useEffect(() => {
    if (wallet?.getAccountId())
      setUser(wallet?.getAccountId());
  }, [])

  return (
    <>
      <Head>
        <title>Next Near App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      </main>
    </>
  )
}
