import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { signIn, signOut, wallet } from '@/near/near-setup'
import { Navbar } from '@/components/navbar'
import { Content } from '@/components/content'
import { Sidebar } from '@/components/sidebar'
import { categories } from '@/mock'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [user, setUser] = useState<string | null>(null)

  useEffect(() => {
    if (wallet?.getAccountId())
      setUser(wallet?.getAccountId());
  }, [])

  return (
    <>
      <Head>
        <title>Next Near App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
      </main>
    </>
  )
}
